version: "3.9"

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - url-shortener-network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    ports:
      - "6432:5432"
    volumes:
      - ./docker/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./docker/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    restart: unless-stopped
    networks:
      - url-shortener-network

  backend:
    image: url-shortener-backend:v1
    container_name: url-shortener-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env

    depends_on:
      - pgbouncer
      - redis-stack
    networks:
      - url-shortener-network
    restart: unless-stopped

  worker:
    image: url-shortener-worker:v1

    build:
      context: .
      dockerfile: ./Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - redis-stack
      - pgbouncer
      - backend
    networks:
      - url-shortener-network
    restart: unless-stopped
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - url-shortener-network
    depend-on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  redis-data:

networks:
  url-shortener-network:
    driver: bridge
