events {}
http{
    upstream proxy{
        server backend-backend-1:4000 max_files=3 fail_timeout=30s
        server backend-backend-2:4000 max_files=3 fail_timeout=30s
        server backend-backend-3:4000 max_files=3 fail_timeout=30s
        keepalive 32
    }
    server{
        listen:80;
        location/{
            proxy_http_version: 1.1
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded 
            proxy_set_header X-Forwarded-Proto $scheme
            proxy_set_header  X-Forwarded-Host $host
            proxy_set_header Connection ""; 
            proxy_pass http://proxy
        }
    }
}